name: Run tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Neovim
      uses: rhysd/action-setup-vim@v1
      with:
        neovim: true
        version: v0.11.2

    - name: Install Just
      uses: extractions/setup-just@v3

    - name: Install Node
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install tree-sitter CLI
      run: npm install -g tree-sitter-cli

    - name: Run tests
      run: just test
